---
language: python
services: docker

env:
  global:
    - ROLE_NAME: nginx_exporter
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: debian9

install:
  # Install test dependencies.
  - pip install molecule docker ansible

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
